- name: "Configuring machine"
  hosts: localhost
  roles:
    - role: homebrew
      tags: homebrew
    - role: dotfiles
      tags: dotfiles
  tasks:
    - name: Displaying message that finished
      ansible.builtin.debug:
       msg: "Done!"
